package generator

import (
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strings"
	"unicode"
)

func Generate(dir, packageName, output string) error {
    messages, err := ParseDir(dir)
    if err != nil {
        return err
    }

    var b strings.Builder
    b.WriteString("// Code generated by itskreisler/i18n-go. DO NOT EDIT.\n\n")
    b.WriteString("package " + packageName + "\n\n")
    b.WriteString("import i18n \"github.com/itskreisler/i18n-go\"\n\n")
    b.WriteString("const (\n")

    used := map[string]int{}
    for _, message := range messages {
        name := ExportedName(message.ID)
        used[name]++
        if used[name] > 1 {
            name = fmt.Sprintf("%s%d", name, used[name])
        }
        b.WriteString(fmt.Sprintf("\t%s i18n.Key = %q\n", name, message.ID))
    }

    b.WriteString(")\n")

    formatted, err := format.Source([]byte(b.String()))
    if err != nil {
        return err
    }

    return os.WriteFile(output, formatted, 0o644)
}

var nonAlpha = regexp.MustCompile(`[^a-zA-Z0-9]+`)

func ExportedName(id string) string {
    parts := strings.FieldsFunc(id, func(r rune) bool {
        return nonAlpha.MatchString(string(r))
    })

    var b strings.Builder
    for _, part := range parts {
        r := []rune(part)
        if len(r) == 0 {
            continue
        }
        r[0] = unicode.ToUpper(r[0])
        b.WriteString(string(r))
    }

    if b.Len() == 0 {
        return "Key"
    }

    name := b.String()
    if unicode.IsDigit([]rune(name)[0]) {
        return "Key" + name
    }
    return name
}
