// Code generated by itskreisler/i18n-go. DO NOT EDIT.

package locales

import i18n "github.com/itskreisler/i18n-go"

const (
	Hello         i18n.Key = "hello"
	Items         i18n.Key = "items"
	SettingsTitle i18n.Key = "settings.title"
	Welcome       i18n.Key = "welcome"
	WelcomeUser   i18n.Key = "welcome_user"
)
